version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_OLLAMA_API_URL=http://10.0.0.10:11434
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - booner-mcp-network

  api:
    image: booner-mcp-api
    build:
      context: ../booner-mcp-api # Adjust path if API code is elsewhere
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - OLLAMA_API_URL=http://10.0.0.10:11434
      - AUTH_SECRET=YOUR_AUTH_SECRET_HERE # Change this in production
      - DATABASE_URL=sqlite:///data/database.db
    volumes:
      - mcp-data:/data
    restart: unless-stopped
    networks:
      - booner-mcp-network

volumes:
  mcp-data:

networks:
  booner-mcp-network:
    driver: bridge
