# NOTE: This docker-compose file is for standalone deployment of the web UI only.
# For full system deployment, use the docker-compose.yml in the main Booner_MCP directory.

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_OLLAMA_API_URL=${NEXT_PUBLIC_OLLAMA_API_URL:-http://10.0.0.10:11434}
      - NEXT_PUBLIC_AUTH_SECRET=${AUTH_SECRET:-your_default_auth_secret}
    restart: unless-stopped

# No API service defined here - this is only for the web UI component
# For full system deployment, use the docker-compose.yml in the main Booner_MCP directory
